/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ANGULARRT
#define ANGULARRT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooRealVar.h"
#include "RooAbsCategory.h"
#include "RooLegendre.h"
#include "RooFormulaVar.h"

class AngularRT : public RooAbsPdf {
 protected:

  RooRealProxy ctK ;
  RooRealProxy ctL ;
  RooRealProxy phi ;
  RooRealProxy Fl ;
  RooRealProxy P1 ;
  RooRealProxy P2 ;
  RooRealProxy P3 ;
  RooRealProxy P4p ;
  RooRealProxy P5p ;
  RooRealProxy P6p ;
  RooRealProxy P8p ;
  
  Double_t evaluate() const ;

  std::vector < RooLegendre* > vectFuncLegCosK;
  std::vector < RooLegendre* > vectFuncLegCosL;
  std::vector < RooFormulaVar* > vectFuncPoly;

 public:
  AngularRT() {} ; 
  AngularRT(const char *name, const char *title,
	    RooAbsReal& _ctK,
	    RooAbsReal& _ctL,
	    RooAbsReal& _phi,
	    RooAbsReal& _Fl,
	    RooAbsReal& _P1,
	    RooAbsReal& _P2,
	    RooAbsReal& _P3,
	    RooAbsReal& _P4p,
	    RooAbsReal& _P5p,
	    RooAbsReal& _P6p,
	    RooAbsReal& _P8p);
  AngularRT(const AngularRT& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new AngularRT(*this,newname); }
  inline virtual ~AngularRT() { }

  ClassDef(AngularRT,1) // PDF for angular decay rate description
    };
 
#endif
